spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/blogsearch
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: h2


propterties:
  kakao:
    url: "https://dapi.kakao.com"
    restkey: KakaoAK 332a90419ced30f3ff3eefe4b0ce8f3c



thread-pool:
  core-size: 10
  max-size: 50
  queue-capacity: 100